name: Expo Prebuilds

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prebuild:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [android, ios]
        include:
          - os: ubuntu-latest
            platform: android
          - os: macos-latest
            platform: ios

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install dependencies
        run: npm install
      - name: Prebuild for ${{ matrix.platform }}
        run: npx expo prebuild --platform ${{ matrix.platform }}
        working-directory: packages/my-app

      - name: Build Android App
        if: matrix.platform == 'android'
        run: ./gradlew assembleRelease
        working-directory: packages/my-app/android

      - name: Build iOS App
        if: matrix.platform == 'ios'
        run: |
          xcodebuild -workspace my-app.xcworkspace \
            -scheme my-app \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build
        working-directory: packages/my-app/ios
