name: Publish

on:
  push:
    branches:
      - master

jobs:
  easUpdate:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - run: volta install node@latest npm@latest
      - name: Install dependencies
        run: npm install
      - run: volta install eas-cli@latest
      - run: ./eas-update-local.sh
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
